### ISSUE TITLE
anyarray_uniq fails when first element of array is null

### ISSUE THREAD

**Issue by hubrix** [JDBurnZ/postgresql-anyarray#7]
anyarray_uniq(ARRAY[NULL, 'bob', NULL, 'bob']) = [null]
anyarray_uniq(ARRAY['',NULL, 'bob', NULL, 'bob']) = ['', 'bob']

**Comment by JDBurnZ** [comment]
Thanks for reporting this. Looks like both outputs are technical broken, as I'd expect a resulting output similar to:

anyarray_uniq(ARRAY[NULL, 'bob', NULL, 'bob']) = [NULL, 'bob']
anyarray_uniq(ARRAY['',NULL, 'bob', NULL, 'bob']) = ['', NULL, 'bob']

I'll see what I can do to remediate. This is due to the function using `val = ANY(array)` which will always returns NULL rather than TRUE or FALSE when `val` is NULL.

**Comment by JDBurnZ** [comment]
Alright, fixed. When using the updated version of anyarray_unique:

SELECT ANYRRAY_UNIQ(ARRAY[NULL, 'bob', NULL, 'bob']::text[])
Yields: {NULL,bob}

SELECT ANYARRAY_UNIQ(ARRAY['', NULL, 'bob', NULL, 'bob']::text[])
Yields: {"",NULL,bob}
